USE SQL_STORE;

SELECT
  ORDER_ID,
  FIRST_NAME,
  LAST_NAME,
  O.CUSTOMER_ID
FROM
  ORDERS    O
  INNER JOIN CUSTOMERS C
  ON O.CUSTOMER_ID = C.CUSTOMER_ID;

-- new ex
SELECT
  OI.ORDER_ID,
  OI.PRODUCT_ID,
  NAME,
  ORDER_DATE,
  OI.UNIT_PRICE,
  QUANTITY
FROM
  ORDER_ITEMS OI
  INNER JOIN ORDERS O
  ON OI.ORDER_ID = O.ORDER_ID
  INNER JOIN PRODUCTS P
  ON OI.PRODUCT_ID = P.PRODUCT_ID